% This script trains the FBCSP algorith to perform the experimental protocol designed
% according to BCI competitions' paradigms for motor imagery.
%
% Motor imagery-related EEG is acquired from 8 channels: Fz,C3, Cz,
% C4, Pz, PO7, PO8, Oz; the Unicorn is used to acquire the EEG signal.
% Reference and bias were placed at left and right mastoids.
% 
% The BLOCK0 is here considered, i.e. motor imagery without feedback.
%
% These data will be used for analysis of the motor imagery of a specific
% subject with the specific setup, at varying time windows.
%
%  authors:         A. Natalizio, A. Esposito
%  correspondence:  anthony.esp@live.it
%  last update:     2022/02/15
%  edit on 2024/03/13

name = 'Experimental notes';
prompt = {'Soggetto (CogNom)'; 'Sessione'; 'Gruppo'; 'Side'};
formats = struct('type', {}, 'style', {}, 'items', {}, 'format', {});

% Subject
formats(1,1).type   = 'edit';
formats(1,1).format = 'text';
% Session
formats(2,1).type   = 'edit';
formats(2,1).format  = 'integer';
% Group
formats(3,1).type   = 'list';
formats(3,1).style = 'togglebutton';
formats(3,1).items  = {'Control','Neurofeedback'};
% Side
formats(4,1).type   = 'list';
formats(4,1).style = 'togglebutton';
formats(4,1).items  = {'Left','Right'};

answ_notes = inputsdlg(prompt, name, formats);

if answ_notes{3} == 1
    answ_notes{3} = 'control';
elseif answ_notes{3} == 2
    answ_notes{3} = 'neurofeedback';
end

notes.subject = answ_notes{1};
notes.session = answ_notes{2};
notes.group = answ_notes{3};
notes.side = answ_notes{4};

% check how many files already exist for block 0
files = dir(['Data/',notes.subject,'/S',num2str(notes.session),'/',...
    notes.subject,'_S',num2str(notes.session),'_B0*.mat']);
nf = length(files) + 1;

% if length(files)<1
%     StatoFisicoMentale.beginning = intervistaStatoFisicoMentale(1);
%     StatoFisicoMentale.beforeMI = intervistaStatoFisicoMentale(2);
%     % Last part after NF
% else
%     % from previous run
%     prev = load([files(1,1).folder,'\',files(1,1).name]);
%     StatoFisicoMentale = prev.StatoFisicoMentale;
% end

clear answ_notes defaultanswer formats name;

% Unicorn sampling frequency
fs = 250;
% SET THE FOLLOWING BEFORE STARTING NEW SUBJECT
% experimental notes (more info are present in the questionnaire)
notes.block = 0;

notes.channels = {'Fz', 'C3', 'Cz', 'C4', 'Pz', 'PO7', 'PO8', 'Oz'};
notes.reference = 'right mastoid';
notes.bias = 'left mastoid';
%% Execute Simulink model

%% Adjust data from Simulink
% This main script saves the data recorded in Simulink
% Label (generated by Unity)
y = out.labels(8:find(out.labels == 10)-1);
y(y == 35) = [];
y(y == 49) = 3;  %rest
y(y == 50) = 2;  %right

% EEG signal
eeg_C1 = squeeze(out.ScopeData{2}.Values.Data);
eeg_C2 = squeeze(out.ScopeData{3}.Values.Data);
eeg_C3 = squeeze(out.ScopeData{4}.Values.Data);
eeg_C4 = squeeze(out.ScopeData{5}.Values.Data);
eeg_C5 = squeeze(out.ScopeData{6}.Values.Data);
eeg_C6 = squeeze(out.ScopeData{7}.Values.Data);
eeg_C7 = squeeze(out.ScopeData{8}.Values.Data);
eeg_C8 = squeeze(out.ScopeData{9}.Values.Data);

filt_eeg = out.FilteredEEG;

% Trials
tr_start_sec = find(diff(out.ScopeData{1}.Values(:,1).Data(:,1))>0);

% ask for eventual trials with artifacts
answer = inputdlg('Enter space-separated numbers:', 'Trials with artifacts', [1 50]);
user_val = str2double(split(answer{1},' '));
artifacts = zeros(length(y),1);
try
    artifacts(user_val) = 1;
catch
    % do nothing
end

% save experimental data
mh = msgbox('Saving experimental data...','Terminated');
       
% rearranging data format
clear data
data.X = [eeg_C1, eeg_C2, eeg_C3, eeg_C4, eeg_C5, eeg_C6, eeg_C7, eeg_C8];
data.X_filt = filt_eeg;
data.trial = tr_start_sec;
data.y = y;
data.fs = fs;
data.classes = [{'right'},{'rest'}];
data.artifacts = logical(artifacts);
% data.gender = StatoFisicoMentale.beginning.sex;
% data.age = StatoFis icoMentale.beginning.age;

data = {data};

pause(1)
delete(mh);
clearvars -except data notes tr_param nf files;% StatoFisicoMentale;

% save also current time
notes.time = datestr(now, 'yyyy-mm-dd HH-MM');

%{
% Make a new folder if it not exist yet
if ~exist(['Data/',notes.subject,'/S',num2str(notes.session)]) %#ok!
    mkdir(['Data/',notes.subject,'/S',num2str(notes.session)])
end
%}
% Check how many B0 runs the control group performs. If they are equal to
% five, hence, administer the "afterMI" part of the questionnaire
% if notes.group == "control"
%     if length(files) == 5
%         StatoFisicoMentale.afterMI = intervistaStatoFisicoMentale(3);
%     end
% end
save(['DATA/',notes.subject, '_S', num2str(notes.session), '_B', num2str(notes.block), '_', num2str(nf), '.mat']);
%save(['DATA/',notes.subject,'/S',num2str(notes.session),'/',notes.subject, '_S', num2str(notes.session), '_B', num2str(notes.block), '_', num2str(nf), '.mat']);

% save also the trained model for current feedback